### ISSUE TITLE
Как правильно вводить токен?

### ISSUE THREAD

**Issue by Asliasl** [N0t-Ex1st/Discrash#1]

**Comment by N0t-Ex1st** [comment]
В дискорде вышла Обнова для ботов, встану с утра всё проверю, если что перепишу и улучшу, а вообще после слов введите токен: нужно просто ввести токен бота

**Comment by Asliasl** [comment]
Когда удалил проверку длинны токена

**Comment by Asliasl** [comment]
все заработало

**Comment by N0t-Ex1st** [comment]
спасибо, сейчас пофикшу

**Comment by N0t-Ex1st** [comment]
я проверил, все работает
